name: chainchat
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  local_auth: ^2.1.0
  url_launcher: ^6.0.20
  shared_preferences: ^2.0.0
  sqflite: ^2.3.3+1
  http: ^0.13.3
  image_picker: ^0.8.5+3
  dio: ^5.1.2
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.0
  permission_handler: ^10.2.0
  cupertino_icons: ^1.0.6
  sui: ^0.2.1
  flutter_ipfs: ^0.0.2
  lottie: ^1.2.1
  fluttertoast: ^8.2.1
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon/